name: PlatformIO CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PlatformIO environment
        run: |
          apt-get update
          apt-get install -y cmake
          curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
          python3 get-platformio.py
      - name: Run PlatformIO
        run: |
          export PATH=$PATH:~/.platformio/penv/bin
          pio run -e leocore
