name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clang-format_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check formatting
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "18"
          check-path: "App"
          fallback-style: "LLVM"
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Prepare Nix development environment
        uses: rrbutani/use-nix-shell-action@v1.1.0
        with:
          devShell: .#buildenv
      - name: Run CMake (configure)
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "default"
      - name: Run CMake (Debug build)
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "default"
          buildPreset: "Debug"
      - name: Run CMake (Release build)
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "default"
          buildPreset: "Release"
